### ISSUE TITLE
Remote is running but can't get it to connect with firestick 4K

### ISSUE THREAD

**Issue by davidchezmoa** [ZaneH/FireTVRemote-Node#13]
I setup a new ubuntu container, set everything up and use latest adb tool version.
But the web ui say "connected" but doesn't do anything, so I try to send adb command directly from the server and it work like a charm.

For instance the "Home" key is this command and work ok
root@ubuntu:~/firetv-remote/platform-tools# ./adb shell input keyevent 3

but the log of the remote doesn't really show any feedback:
root@ubuntu:~/firetv-remote# npm run start

> firetv-remote@0.1.0 start
> node ./bin/www

Connecting...
POST / 200 25.409 ms - 23
POST / 200 4.216 ms - 20

Nothing happen on the firestick.

**Comment by davidchezmoa** [comment]
User error sorry

**Comment by lxender** [comment]
@davidchezmoa How did you fix it? I'm stuck on the same problem. However adb just works from console, not from the web ui

**Comment by davidchezmoa** [comment]
@lxender To be honest I forgot what I did, but I actually ditch this entire thing and build an integration in home assistant, so my remote for firestick is now directly in home assistant.

![Image](https://github.com/user-attachments/assets/bccbd9f7-bbfc-4266-a475-37aba01fd8d5)
