### ISSUE TITLE
Cloned, tried to run, but nothing happens

### ISSUE THREAD

**Issue by eladkatz** [ZaneH/FireTVRemote-Node#2]
when I enter node app.js nothing happens, it just shows a new line
Any idea why?

**Comment by eladkatz** [comment]
Was able to workaround it by running node ./bin/www instead of node app.js and opening the browser to localhost:3000

**Comment by eladkatz** [comment]
Not sure if this is related, but I could not control the fire tv, even though the connection was successful

**Comment by ZaneH** [comment]
There hasn’t been a commit in 4 years
Likely means it’s not maintained

**Comment by ZaneH** [comment]
Apologies, the readme was incorrect, see #5 for the fix.
